[postgres]
host=dpg-cggclf02qv28tc396eng-a
port=5432
dbname=base_vhom
user=base_vhom_user
password=8xUvM1YA3iw7Rjb1FxPTkgRf2xEFl87T



[theme]
base="light"
primaryColor="#4070d8"
backgroundColor="#eff0f3"
secondaryBackgroundColor="#cfdfef"
